### PR TITLE
Added Command Line Interface

### PR DESCRIPTION
**Pull request by GitBruno**
Hey, added a command line interface option for package signing that includes a prompt for p12 password. Making it easy to save sign command in the package script.

### CODE REVIEW

**Comment by codearoni** [comment]
While I appreciate the merit of a cli interface, it's current impl is not something I'm ready to release.

I've always abhorred third party dependencies, but after the flatmap-stream disaster last month, my spidey sense has been amplified.

If you make an implementation using node's readline API with no external deps, I'll look it over again.

There also may be some changes related styling, but those are minor.

The concept is sound and I like the test(s). If you want to do a vanilla node implementation, I'll look it over again

**Comment by GitBruno** [comment]
Thanks for the comment! I understand your concerns. I personally don't believe that a vanilla implementation is more secure. But agree that minimising dependencies is a good thing generally. 

I have added two packages:

  - 1: Commander (Has no dependencies)

This is a clean package and I believe it would be a waste of my time to re-write. I'd rather contribute to the package if there is a problem. Maybe review this package as if it was vanilla code?

  - 2: Prompt (Has dependencies)

I understand your concern here and like your suggestion of using Node's Readline API. Will update my PR to reflect this. Stay tuned...

**Comment by codearoni** [comment]
I'm firm on this. However, if you are steadfast on commander, might I recommend publishing your own cli module? cep-packager and create-zxp are two modules that do something similar.

You can publish your own zxp module using this one as a dep. Then you can maintain it with the latest commander package, independent of zxp-sign-cmd

**Comment by GitBruno** [comment]
Good idea, [working on it!](https://github.com/CoverBuilder/zxp-builder)

Thanks,

**Comment by codearoni** [comment]
Your other changes will go into a future patch release

**Pull request closed without merging**
